databases:
  - name: readUPdb
    plan: free
    databaseName: readUP_db
    user: readUP_user

services:
  - type: web
    plan: free
    name: ReadUP
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:Read_UP_project -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: readUPdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4